### ISSUE TITLE
Latest version doesn't have Ruby 3.3.0 compatible precompiled binaries

### ISSUE THREAD

**Issue by casperisfine** [Shopify/blake3-rb#4]
Ref: https://rubygems.org/gems/blake3-rb/versions/1.5.3-arm64-darwin

As a result to compile it you need to install quite a lot of extra system dependencies such as `libclang` and `libllvm`.

**Comment by ianks** [comment]
Done -> https://rubygems.org/gems/blake3-rb/versions/1.5.4-x86_64-darwin

**Comment by casperisfine** [comment]
❤️
